/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary': '#712ae2',
        'on-secondary-fixed': '#25005a',
        'on-primary-container': '#dad7ff',
        'outline-variant': '#c7c4d8',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#d2bbff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-dim': '#cbdbf5',
        'on-tertiary-container': '#67f4b7',
        'primary-fixed': '#e2dfff',
        'surface-container': '#e5eeff',
        'primary-container': '#4f46e5',
        'surface-container-lowest': '#ffffff',
        'outline': '#777587',
        'tertiary-container': '#006e4b',
        'tertiary': '#005338',
        'primary-fixed-dim': '#c3c0ff',
        'secondary-fixed': '#eaddff',
        'on-primary-fixed-variant': '#3323cc',
        'surface-tint': '#4d44e3',
        'background': '#f8f9ff',
        'tertiary-fixed': '#6ffbbe',
        'secondary-container': '#8a4cfc',
        'inverse-primary': '#c3c0ff',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'on-secondary-container': '#fffbff',
        'surface-container-low': '#eff4ff',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        'tertiary-fixed-dim': '#4edea3',
        'surface-bright': '#f8f9ff',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#002113',
        'primary': '#3525cd',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#001069',
        'on-tertiary-fixed-variant': '#005236',
        'surface': '#f8f9ff',
        'on-surface': '#0b1c30',
        'on-background': '#0b1c30',
        'inverse-surface': '#213145',
        'on-tertiary': '#ffffff',
        'surface-variant': '#d3e4fe',
        'on-surface-variant': '#464555',
        'on-secondary-fixed-variant': '#5a00c6',
      },
      fontFamily: {
        headline: ['var(--font-plus-jakarta)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      boxShadow: {
        'ambient': '0 20px 40px -15px rgba(53, 37, 205, 0.08)',
        'ambient-lg': '0 20px 60px -10px rgba(53, 37, 205, 0.14)',
      },
    },
  },
  plugins: [],
};
